sudo: false
language: node_js
node_js: stable
cache: 
  directories:
    - node_modules
install:
  - npm install
branches:
  only:
    - master # build master branch only
script:
  - hexo clean && hexo algolia && hexo g
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: master
  local-dir: public
