language: node_js
node_js:
  - 16
sudo: required

# Travis-CI Caching
cache:
  directories:
    - node_modules

# S: Build Lifecycle
install:
  - npm install

before_script:
 # - npm install -g gulp


script:
  - hexo clean && hexo generate

after_success:
  - cd ./public
  - git init
  - git config user.name "siwting"
  - git config user.email "siwting90@gmail.com"
  - git add .
  - git commit -m "Update docs"
  - git remote add origin https://${GH_REF}"
  - git checkout -b gh-pages
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" gh-pages:gh-pages

# after_script:
#   - cd ../
#   - chmod +x ./bin/autoissue
#   - ./bin/autoissue
# E: Build LifeCycle

branches:
  only:
    - master
env:
 global:
   - GH_REF: github.com/siwting/blog.git
